export enum ChatsActionType {
  FETCH_USER_CHATS_LOADING = "FETCH_USER_CHATS_LOADING",
  FETCH_USER_CHATS_SUCCESS = "FETCH_USER_CHATS_SUCCESS",
  FETCH_USER_CHATS_ERROR = "FETCH_USER_CHATS_ERROR",
  SET_CURRENT_CHAT_ID = "SET_CURRENT_CHAT_ID"
}
