export enum MessageActionType {
  FETCH_ALL_CHAT_MESSAGES_LOADING = "FETCH_ALL_CHAT_MESSAGES_LOADING",
  FETCH_ALL_CHAT_MESSAGES_SUCCESS = "FETCH_ALL_CHAT_MESSAGES_SUCCESS",
  FETCH_ALL_CHAT_MESSAGES_ERROR = "FETCH_ALL_CHAT_MESSAGES_LOADING,",
  ADD_NEW_MESSAGE_LOADING = "ADD_NEW_MESSAGE_LOADING",
  ADD_NEW_MESSAGE_SUCCESS = "ADD_NEW_MESSAGE_SUCCESS",
  ADD_NEW_MESSAGE_ERROR = "ADD_NEW_MESSAGE_ERROR",
}
