export  enum UserActionType {
  SET_AUTH_USER_DATA_SUCCESS = "SET_AUTH_USER_DATA_SUCCESS",
  SET_AUTH_USER_DATA_LOADING = "SET_AUTH_USER_DATA_LOADING",
  SET_AUTH_USER_DATA_ERROR = "SET_AUTH_USER_DATA_ERROR",
  CLEAR_USER_DATA = "CLEAR_USER_DATA"
}
